process.on('uncaughtException',e=>{console.error(e.message,e.code??'',e.position??'',e.where??'');process.exit(1);});
import assert from 'node:assert/strict';
import {readFileSync,readdirSync} from 'node:fs';
import {randomUUID,createHash} from 'node:crypto';
import {PGlite} from '../node_modules/.staff-validation/node_modules/@electric-sql/pglite/dist/index.js';
const db=new PGlite();
const id=n=>'00000000-0000-4000-8000-'+String(n).padStart(12,'0');
const query=(s,a=[])=>db.query(s,a);
const value=async(s,a=[])=>(await query(s,a)).rows[0].value;
async function as(n,sql,args=[],role='authenticated'){await db.exec('SET ROLE '+role);await query("select set_config('request.jwt.claim.sub',$1,false)",[n?id(n):'']);try{return await value(sql,args);}finally{await db.exec('RESET ROLE');}}
await db.exec("CREATE ROLE anon; CREATE ROLE authenticated; CREATE ROLE service_role BYPASSRLS; CREATE SCHEMA auth; CREATE TABLE auth.users(id uuid PRIMARY KEY); CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;");
for(const f of readdirSync('supabase/migrations').filter(f=>f.endsWith('.sql')).sort())await db.exec(readFileSync('supabase/migrations/'+f,'utf8'));
await query("insert into app.businesses(id,slug,display_name) values($1,'test','Test'),($2,'other','Other')",[id(1),id(2)]);
await query("insert into app.stores(id,business_id,code,name,address_line1,city,state,pickup_enabled) values($1,$2,'test','Test','Test street','Test city','Test state',true)",[id(10),id(1)]);
await query("insert into app.business_settings(business_id,employee_operational_history_days,require_payment_before_completion,max_order_items,max_order_total_paise) values($1,30,false,20,10000000)",[id(1)]);
for(const [n,b,role] of [[20,1,'OWNER'],[21,1,'OWNER'],[22,1,'EMPLOYEE'],[23,2,'OWNER']]){await query('insert into auth.users values($1)',[id(n)]);await query("insert into app.staff_profiles(id,business_id,auth_user_id,display_name,role) values($1,$2,$1,'Test',$3)",[id(n),id(b),role]);}
await query('insert into app.staff_admin_grants(staff_profile_id) values($1),($2)',[id(20),id(23)]);
const category=await as(20,"select api.save_category(null,'Test',null,0,true) as value");
const rows=[];
for(const [name,basis,grams,count,quantities,price] of [['Raw','RAW_WEIGHT',1000,null,[500,1000],160000],['King Fish','NET_WEIGHT',500,null,[500,1000],80000],['Eggs','TRAY',null,30,[1,2],45000],['Unit','UNIT',null,1,[1,2],100]]){
 const p=await as(20,`select api.save_product(null,$1,$2,'','','','[500,1000]','[{"name":"Whole"}]',true) as value`,[category,name]);
 await as(20,'select api.configure_product_pricing($1,$2,$3,$4,$5,$6,true) as value',[p,basis,grams,count,JSON.stringify(quantities),price]);
 for(const actor of [21,22,23])await assert.rejects(()=>as(actor,'select api.configure_product_pricing($1,$2,$3,$4,$5,$6,true) as value',[p,basis,grams,count,JSON.stringify(quantities),1]),e=>e.code==='42501');
 const o=await as(20,'select api.create_offering($1,$2) as value',[p,id(10)]);
 await as(21,'select api.update_daily_product($1,1,$2,true) as value',[o,price]);
 const prep=await value('select preparation_option_id as value from app.product_preparation_options where product_id=$1',[p]);
 rows.push({p,o,prep,basis,price,quantity:quantities[0]});
}
await query('insert into app.staff_store_assignments(business_id,store_id,staff_profile_id) values($1,$2,$3)',[id(1),id(10),id(22)]);
const start=new Date(Date.now()-86400000).toISOString(),end=new Date(Date.now()+86400000).toISOString();
const saveSQL='select api.save_offer($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) as value';
const offerArgs=(patch={})=>{const o={id:null,store:id(10),version:null,title:'Fresh savings',message:'Fresh offer',kind:'PERCENT',amount:1000,start,end,scope:'STORE',products:[],categories:[],active:true,...patch};return [o.id,o.store,o.version,o.title,o.message,o.kind,o.amount,o.start,o.end,o.scope,o.products,o.categories,o.active];};
const save=(patch={},actor=21)=>as(actor,saveSQL,offerArgs(patch));
const offer=await save();
const fixed=await save({title:'Selected fish',kind:'FIXED',amount:15000,scope:'PRODUCTS',products:[rows[1].p]},20);
for(const actor of [22,23])await assert.rejects(()=>save({},actor),e=>e.code==='42501');
await assert.rejects(()=>as(null,saveSQL,offerArgs(), 'anon'),e=>e.code==='42501');
await assert.rejects(()=>save({scope:'PRODUCTS',products:[randomUUID()]}));
await assert.rejects(()=>save({scope:'PRODUCTS',products:[]}));
await assert.rejects(()=>save({end:start}));
await assert.rejects(()=>save({amount:10001}));
await assert.rejects(()=>save({id:offer,version:999}),e=>e.code==='40001');
await save({title:'Future',start:end,end:new Date(Date.now()+172800000).toISOString()});
await save({title:'Expired',start:new Date(Date.now()-172800000).toISOString(),end:start});
await save({title:'Inactive',active:false});
const current=await as(null,'select api.store_offers($1) as value',[id(10)],'anon');
assert.equal(current.length,2);
const employee=await as(22,'select api.offer_workspace($1) as value',[id(10)]);
assert.equal(employee.current.length,2);assert.equal(employee.offers,undefined);assert.equal(employee.products,undefined);
await assert.rejects(()=>as(23,'select api.offer_workspace($1) as value',[id(10)]),e=>e.code==='42501');
console.log('PASS OWNER/ADMIN management, EMPLOYEE read-only, tenant isolation, validation, current-only publication');
const payload={method:'STORE_PICKUP',mobile:'9876543210',paymentMethod:'CASH',items:rows.map(r=>({productId:r.p,preparationId:r.prep,...(r.basis==='RAW_WEIGHT'?{rawWeightGrams:r.quantity}:{quantity:r.quantity}),instructions:''}))};
const quote=(p=payload)=>as(null,'select api.checkout_quote($1,$2) as value',[id(10),JSON.stringify(p)],'trait_checkout');
let q=await quote();assert.equal(q.subtotalPaise,205100);assert.equal(q.discountPaise,20510);assert.equal(q.totalPaise,184590);assert.equal(q.offer.id,offer);
await assert.rejects(()=>quote({...payload,discountPaise:999999}));
await assert.rejects(()=>quote({...payload,offerId:fixed}));
const token=randomUUID().replaceAll('-','').repeat(2);
const placeArgs=[id(10),randomUUID(),JSON.stringify(payload),q.quoteDigest,createHash('sha256').update(token).digest('hex'),end];
const place=(args=placeArgs)=>as(null,'select api.place_order($1,$2,$3,$4,$5,$6) as value',args,'trait_checkout');
const placed=await place();assert.equal(placed.totalPaise,184590);
assert.equal(await value('select amount_paise as value from app.payments where order_id=$1',[placed.id]),184590);
assert.equal(await value('select discount_paise as value from app.orders where id=$1',[placed.id]),20510);
const tracked=await as(null,'select api.track_order($1) as value',[token],'anon');assert.equal(tracked.discountPaise,20510);assert.equal(tracked.totalPaise,184590);
await assert.rejects(()=>query('update app.orders set discount_paise=0 where id=$1',[placed.id]));
await save({id:offer,version:1,active:false});
assert.equal((await place()).id,placed.id);
await assert.rejects(()=>place([...placeArgs.slice(0,1),randomUUID(),...placeArgs.slice(2)]),e=>e.code==='40001');
q=await quote();assert.equal(q.discountPaise,15000);assert.equal(q.offer.id,fixed);assert.equal(q.totalPaise,190100);
q=await quote({...payload,items:[payload.items[0]]});assert.equal(q.discountPaise,0);
await query('update app.stores set delivery_enabled=true where id=$1',[id(10)]);
await as(21,"select api.save_delivery_area(null,$1,null,'560001','Test area',3000,200000,true) as value",[id(10)]);
const delivery=await quote({...payload,method:'HOME_DELIVERY',name:'Test',address:{line1:'Test road',city:'Test city',state:'Test state',pincode:'560001'}});
assert.equal(delivery.discountPaise,15000);assert.equal(delivery.deliveryFeePaise,3000);assert.equal(delivery.totalPaise,193100);
console.log('PASS server-only best discount, product scope, payment amount, immutable snapshots, stale quote and idempotent retry');
await save({id:fixed,version:1,title:'Selected fish',kind:'FIXED',amount:90000,scope:'PRODUCTS',products:[rows[1].p]});
q=await quote();assert.equal(q.discountPaise,80000); // Never discount unrelated items.
const parent=await as(20,"select api.save_category(null,'Parent',null,0,true) as value");
await as(20,"select api.save_category($1,'Test',$2,0,true) as value",[category,parent]);
const categoryOffer=await save({kind:'PERCENT',amount:1250,scope:'CATEGORIES',categories:[parent]});
await save({id:fixed,version:2,active:false});
q=await quote();assert.equal(q.discountPaise,25637);assert.equal(q.offer.id,categoryOffer); // Floor fractional paise.
await save({id:categoryOffer,version:1,kind:'FIXED',amount:100000000});
q=await quote();assert.equal(q.discountPaise,205099);assert.equal(q.totalPaise,1);
await save({id:categoryOffer,version:2,active:false});
q=await quote();assert.equal(q.discountPaise,0);assert.equal(q.totalPaise,205100);
const expiryOffer=await save({end});q=await quote();
await save({id:expiryOffer,version:1,start:new Date(Date.now()-172800000).toISOString(),end:start});
await assert.rejects(()=>place([id(10),randomUUID(),JSON.stringify(payload),q.quoteDigest,placeArgs[4],end]),e=>e.code==='40001');
for(const role of ['anon','authenticated','service_role','trait_checkout','trait_payment_verifier']){
 assert.equal(await value("select has_table_privilege($1,'app.offers','SELECT,INSERT,UPDATE,DELETE') as value",[role]),false);
 assert.equal(await value("select has_function_privilege($1,'app.offer_discount(uuid,jsonb,timestamptz)','EXECUTE') as value",[role]),false);
}
assert.equal(await value("select relrowsecurity and relforcerowsecurity as value from pg_class where oid='app.offers'::regclass"),true);
console.log('PASS category descendants, integer rounding, fixed cap, expiry, no-offer fallback, forced RLS and RPC-only access');
await db.close();
