"use client";
import { useState } from "react";
import Image from "next/image";
import { products as source } from "@/data/catalog";
import { money, type PreviewRole, type Section } from "@/lib/admin/presentation";
import { Badge, Editor, Panel, type Edit } from "./ui";
type Product = { id: string; name: string; local: string; category: string; price: number; available: boolean; active: boolean; featured: boolean; description: string; image: string; weights: string; preparations: string; losses: string };
type Category = { name: string; parent: string; active: boolean; sort: number };
const initial: Product[] = source.map(p => ({ id: p.id, name: p.name, local: p.localName ?? "", category: p.category === "seafood" ? "Seafood & Prawns" : p.category[0].toUpperCase() + p.category.slice(1), price: p.pricePerKg * 100, available: p.available, active: true, featured: p.id === "seer", description: p.cut, image: p.image, weights: p.selectableWeightsGrams.join(", "), preparations: p.preparationOptions.map(o => o.label).join(", "), losses: p.cleaningLossPercent === undefined ? "" : p.preparationOptions.filter(o => o.removesCleaningWaste).map(o => `${o.label}:${p.cleaningLossPercent}`).join(", ") }));
export function Catalogue({ role, section, store, notify }: { role: PreviewRole; section: Section; store: string; notify: (message?: string) => void }) {
 const [products, setProducts] = useState(initial);
 const [categories, setCategories] = useState<Category[]>([{ name: "Fish", parent: "None", active: true, sort: 1 }, { name: "Seafood & Prawns", parent: "Fish", active: true, sort: 2 }, { name: "Chicken", parent: "None", active: true, sort: 3 }, { name: "Mutton", parent: "None", active: true, sort: 4 }]);
 const [query, setQuery] = useState(""); const [filter, setFilter] = useState("All"); const [edit, setEdit] = useState<Edit | null>(null);
 const [history, setHistory] = useState<string[]>([]); const [branch, setBranch] = useState<Record<string, { price: number; available: boolean }>>(() => Object.fromEntries(initial.map(p => [p.id, { price: p.price, available: p.available }])));
 if (role === "employee" || (role !== "admin" && section !== "prices")) return null;
 const matches = (value: string) => value.toLowerCase().includes(query.trim().toLowerCase());
 function editProduct(product?: Product) {
 if (role !== "admin") return;
 setEdit({ title: product ? "Edit product" : "Add product", fields: [
 { name: "name", label: "Product name", value: product?.name }, { name: "local", label: "Local name", value: product?.local, required: false },
 { name: "category", label: "Category", value: product?.category, options: categories.map(c => c.name) }, { name: "description", label: "Description / cut", value: product?.description, type: "textarea" },
 { name: "weights", label: "Allowed raw weights (grams)", value: product?.weights ?? "500, 1000, 1500, 2000", help: "Comma-separated positive whole grams." },
 { name: "preparations", label: "Preparation choices", value: product?.preparations ?? "Whole, Cleaned", help: "Comma-separated choices." },
 { name: "losses", label: "Cleaning loss estimates by preparation", value: product?.losses ?? "", required: false, help: "Optional: Cleaned:25, Curry Cut:20. Omit preparations without configured loss." },
 { name: "image", label: "Product image", value: product?.image ?? initial[0].image, options: [...new Set(initial.map(p => p.image))], help: "Existing local assets only. Secure uploads await integration." },
 { name: "featured", label: "Featured", value: product?.featured ? "Yes" : "No", options: ["No", "Yes"] }, { name: "active", label: "Listing status", value: product?.active === false ? "Retired" : "Active", options: ["Active", "Retired"] },
 ], save: v => {
 if (!v.name.trim() || !v.preparations.trim()) return "Name and preparation choices cannot be blank.";
 const weights = v.weights.split(",").map(Number); if (weights.some(n => !Number.isSafeInteger(n) || n <= 0) || new Set(weights).size !== weights.length) return "Enter unique positive whole weights, separated by commas.";
 const preparations = v.preparations.split(",").map(p => p.trim()); if (preparations.some(p => !p) || new Set(preparations).size !== preparations.length) return "Enter unique preparation names.";
 if (v.losses.trim()) { const entries = v.losses.split(",").map(entry => entry.trim().split(":")); if (entries.some(([name, percentage]) => !preparations.includes(name) || !percentage?.trim() || !Number.isFinite(Number(percentage)) || Number(percentage) < 0 || Number(percentage) >= 100) || new Set(entries.map(e => e[0])).size !== entries.length) return "Use unique configured preparation names and percentages from 0 to below 100."; }
 const draft: Product = { id: product?.id ?? `draft-${Date.now()}`, image: v.image, price: product?.price ?? 0, available: product?.available ?? false, name: v.name.trim(), local: v.local.trim(), category: v.category, description: v.description, weights: weights.join(", "), preparations: preparations.join(", "), losses: v.losses, featured: v.featured === "Yes", active: v.active === "Active" };
 setProducts(current => product ? current.map(p => p.id === product.id ? draft : p) : [...current, draft]); notify();
 } }); }
 function editCategory(category?: Category) {
 if (role !== "admin") return;
 setEdit({ title: category ? "Edit category" : "Add category", fields: [{ name: "name", label: "Category name", value: category?.name }, { name: "parent", label: "Parent category", value: category?.parent ?? "None", options: ["None", ...categories.filter(c => c.name !== category?.name && c.parent === "None").map(c => c.name)] }, { name: "sort", label: "Display order", value: category?.sort ?? categories.length + 1, type: "number", min: 0 }, { name: "active", label: "Status", value: category?.active === false ? "Retired" : "Active", options: ["Active", "Retired"] }], save: v => {
 const name = v.name.trim(); if (!name || categories.some(c => c !== category && c.name.toLowerCase() === name.toLowerCase())) return "Enter a unique category name.";
 if (category && categories.some(c => c.parent === category.name) && v.parent !== "None") return "A category with children must remain at the top level in this preview.";
 const draft = { name, parent: v.parent, sort: Number(v.sort), active: v.active === "Active" };
 setCategories(current => category ? current.map(c => c === category ? draft : c.parent === category.name ? { ...c, parent: name } : c) : [...current, draft]);
 if (category) setProducts(current => current.map(p => p.category === category.name ? { ...p, category: name } : p)); notify();
 } }); }
 const list = products.filter(p => matches(p.name + p.local) && (filter === "All" || filter === p.category || (filter === "Active" && p.active) || (filter === "Retired" && !p.active)));
 return <><div className="admin-toolbar"><input aria-label="Search catalogue" placeholder={section === "categories" ? "Search categories…" : "Search products…"} value={query} onChange={e => setQuery(e.target.value)} />{section === "catalogue" && <select aria-label="Filter catalogue" value={filter} onChange={e => setFilter(e.target.value)}>{["All", "Active", "Retired", ...categories.map(c => c.name)].map(s => <option key={s}>{s}</option>)}</select>}{section !== "prices" && <button className="admin-button" onClick={() => section === "categories" ? editCategory() : editProduct()}>+ Add {section === "categories" ? "category" : "product"}</button>}</div>
 {section === "catalogue" && <><div className="admin-product-grid">{list.map(p => <article className="admin-product" key={p.id}><div className="admin-product-image"><Image src={p.image} alt={p.name} width={400} height={240} /><Badge>{p.active ? "Active" : "Retired"}</Badge></div><div className="admin-product-body"><span className="admin-kicker">{p.category}{p.featured ? " · Featured" : ""}</span><h2>{p.name}</h2><p>{p.local || p.description}</p><small>{p.preparations}</small><small>Raw weights: {p.weights} g</small><div className="admin-product-footer"><strong>{money(p.price)}<small> / kg · sample</small></strong><button className="admin-text-button" onClick={() => editProduct(p)}>Edit<span className="sr-only"> {p.name}</span> &rarr;</button></div></div></article>)}</div>{!list.length && <div className="admin-empty">No products match these filters.</div>}<p className="admin-muted admin-footnote">New drafts start unavailable. Catalogue changes never rewrite purchased order snapshots.</p></>}
 {section === "categories" && <Panel title="Category structure"><div className="admin-category-list">{categories.filter(c => matches(c.name)).sort((a, b) => a.sort - b.sort).map(c => <div className="admin-category-row" key={c.name}><span className="admin-category-number">{c.sort.toString().padStart(2, "0")}</span><div><h3>{c.parent !== "None" ? "- " : ""}{c.name}</h3><small>{c.parent === "None" ? "Top-level category" : `Under ${c.parent}`} · {products.filter(p => p.category === c.name).length} products</small></div><Badge>{c.active ? "Active" : "Retired"}</Badge><button className="admin-text-button" onClick={() => editCategory(c)}>Edit<span className="sr-only"> {c.name}</span></button></div>)}</div>{!categories.some(c => matches(c.name)) && <div className="admin-empty">No categories found.</div>}</Panel>}
 {section === "prices" && <><div className="admin-notice">Prices are per kilogram of raw weight. Changes append to the sample history; purchased prices stay unchanged.</div><Panel title={`${store === "main" ? "Main store" : "Sample branch"} pricing`}><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Product</th><th>Price / kg</th><th>Availability</th><th>Action</th></tr></thead><tbody>{list.map(p => { const offering = store === "branch" ? branch[p.id] ?? p : p; return <tr key={p.id}><td><strong>{p.name}</strong><small>{p.category}</small></td><td>{money(offering.price)}</td><td><Badge>{offering.available ? "Available" : "Sold Out"}</Badge></td><td><button className="admin-text-button" onClick={() => setEdit({ title: `Price & availability · ${p.name}`, fields: [{ name: "price", label: "Raw-weight price per kg (INR)", type: "number", min: 0.01, max: 1000000, step: "0.01", value: offering.price / 100 }, { name: "available", label: "Availability", options: ["Available", "Sold Out"], value: offering.available ? "Available" : "Sold Out" }, { name: "reason", label: "Reason for change" }], save: v => { if (!v.reason.trim()) return "A change reason is required."; const value = { price: Math.round(Number(v.price) * 100), available: v.available === "Available" }; if (store === "branch") setBranch(current => ({ ...current, [p.id]: value })); else setProducts(current => current.map(item => item.id === p.id ? { ...item, ...value } : item)); setHistory(current => [`${p.name} · ${store === "main" ? "Main store" : "Sample branch"} · ${money(offering.price)} to ${money(value.price)} · ${v.available} · ${v.reason} · Sample owner · ${new Date().toLocaleTimeString()}`, ...current]); notify(); } })}>Update<span className="sr-only"> {p.name}</span></button></td></tr>; })}</tbody></table>{!list.length && <div className="admin-empty">No matching products.</div>}</div></Panel><Panel title="Preview price history">{history.length ? <ul className="admin-history">{history.map((entry, i) => <li key={i}>{entry}</li>)}</ul> : <p className="admin-muted">No changes yet. Update a price to see an entry here.</p>}</Panel></>}
 {edit && <Editor title={edit.title} fields={edit.fields} note={edit.note} onSave={edit.save} onClose={() => setEdit(null)} />}</>;
}

