"use client";
import { useState } from "react";
import { Badge, Editor, Panel, type Edit } from "./ui";
type Employee = { id: string; name: string; email: string; store: string; active: boolean; role: "OWNER" | "EMPLOYEE" };
export function Employees({ notify }: { notify: (message?: string) => void }) {
 const [employees, setEmployees] = useState<Employee[]>([{ id: "owner", name: "Sample owner", email: "owner@example.invalid", store: "All stores", active: true, role: "OWNER" }, { id: "team-a", name: "Sample employee A", email: "team-a@example.invalid", store: "Main store", active: true, role: "EMPLOYEE" }, { id: "team-b", name: "Sample employee B", email: "team-b@example.invalid", store: "Sample branch", active: false, role: "EMPLOYEE" }]);
 const [query, setQuery] = useState(""); const [edit, setEdit] = useState<Edit | null>(null);
 function editEmployee(employee?: Employee) { setEdit({ title: employee ? "Edit employee" : "Draft employee invitation", note: "No invitation is sent and no account is created. Supabase Auth will manage credentials; never enter passwords here.", fields: [{ name: "name", label: "Display name", value: employee?.name }, { name: "email", label: "Work email", type: "email", value: employee?.email }, { name: "store", label: "Assigned store", options: ["Main store", "Sample branch"], value: employee?.store }, { name: "active", label: "Access state", options: ["Active", "Disabled"], value: employee?.active === false ? "Disabled" : "Active" }], save: v => { if (!v.name.trim()) return "Enter a display name."; if (employees.some(e => e.id !== employee?.id && e.email.toLowerCase() === v.email.trim().toLowerCase())) return "This email already has a preview profile."; const draft: Employee = { id: employee?.id ?? `draft-${Date.now()}`, name: v.name.trim(), email: v.email.trim(), store: v.store, active: v.active === "Active", role: "EMPLOYEE" }; setEmployees(current => employee ? current.map(e => e.id === employee.id ? draft : e) : [...current, draft]); notify("Employee draft saved. No account, invitation or live access was changed."); } }); }
 const list = employees.filter(e => (e.name + e.email).toLowerCase().includes(query.trim().toLowerCase()));
 return <><div className="admin-toolbar"><input aria-label="Search team members" placeholder="Search team members…" value={query} onChange={e => setQuery(e.target.value)} /><button className="admin-button" onClick={() => editEmployee()}>+ Draft invitation</button></div><Panel title="Staff & access"><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Team member</th><th>Role</th><th>Store access</th><th>Status</th><th>Manage</th></tr></thead><tbody>{list.map(e => <tr key={e.id}><td><strong>{e.name}</strong><small>{e.email}</small></td><td><Badge>{e.role}</Badge></td><td>{e.store}</td><td><Badge>{e.active ? "Active" : "Disabled"}</Badge></td><td>{e.role === "OWNER" ? <small>Final owner protected</small> : <button className="admin-text-button" onClick={() => editEmployee(e)}>Edit<span className="sr-only"> {e.name}</span></button>}</td></tr>)}</tbody></table>{!list.length && <div className="admin-empty">No matching team members.</div>}</div></Panel><div className="admin-dashboard-grid"><Panel title="Owner access"><p>Business operations: permitted orders, daily prices and availability, employees, payments, reports and normal settings. Catalogue master data is ADMIN-only. The final active owner cannot be removed or demoted.</p></Panel><Panel title="Employee access"><p>Active staff membership and store assignment are required. Employees receive only permitted order operations. Disabled membership must revoke access even for an existing session.</p><button className="admin-button secondary" disabled>Password recovery · integration pending</button></Panel></div>{edit && <Editor title={edit.title} fields={edit.fields} note={edit.note} onSave={edit.save} onClose={() => setEdit(null)} />}</>;
}
