import { ProductChoices } from "./product-choices";
import Link from "next/link";
import { Operations, BusinessPolicy } from "./operations";
import { DeliverySettings } from "./delivery-settings";
import { BusinessReport } from "./report";
import { StaffDirectory } from "./staff-directory";
import { OperationalForm } from "./operational-form";
import { signOut } from "@/app/admin/actions";
import { staffRpc, type StaffContext } from "@/lib/admin/server";
import { canAccessSection, staffSections, type StaffSection } from "@/lib/admin/permissions";
import { sectionLabels } from "@/lib/admin/presentation";
import { DailyProducts, MutationForm, type DailyProduct } from "./live-forms";
type Category={id:string;name:string;parent_id:string|null;sort_order:number;is_active:boolean};
type Product={id:string;category_id:string;name:string;local_name:string;description:string;image_path:string;allowed_weights:number[];preparations:{name:string;cleaning_loss_percent?:number}[];is_active:boolean};
function Active({value=true}:{value?:boolean}) {return <label>Status<select name="active" defaultValue={String(value)}><option value="true">Active</option><option value="false">Retired / inactive</option></select></label>;}
export async function LiveWorkspace({context,token,section,storeId,orderId,days,before,cursor,fromDate,untilDate}:{context:StaffContext;token:string;section:StaffSection;storeId?:string;orderId?:string;days?:number;before?:string;cursor?:string;fromDate?:string;untilDate?:string}) {
 const base="/admin/"+context.role.toLowerCase(); const store=context.stores.find(s=>s.id===storeId)??context.stores[0];
 let content;
 if(section==="orders"||section==="payments"||section==="dashboard") content=<Operations token={token} context={context} store={store?.id} orderId={orderId} section={section} before={before} cursor={cursor}/>;
 else if(section==="reports") content=<BusinessReport token={token} store={store?.id} days={days} fromDate={fromDate} untilDate={untilDate}/>;
 else if(section==="prices") content=store?<><p>Prices are per kilogram of raw weight. Every price change preserves its history. Saving affects future pricing only.</p><DailyProducts products={await staffRpc<DailyProduct[]>(token,"daily_products",{target_store:store.id})}/></>:<p>No accessible stores.</p>;
 else if(section==="catalogue"||section==="categories") {
 const master=await staffRpc<{categories:Category[];products:Product[]}>(token,"catalogue_master");
 content=section==="categories"?<>{[null,...master.categories].map(c=><details key={c?.id??"new"}><summary>{c?.name??"Add category"}</summary><MutationForm kind="master"><input type="hidden" name="kind" value="category"/><input type="hidden" name="id" value={c?.id??""}/><label>Name<input name="name" required defaultValue={c?.name}/></label><label>Parent<select name="parent" defaultValue={c?.parent_id??""}><option value="">None</option>{master.categories.filter(x=>x.id!==c?.id).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Display order<input name="sort" type="number" min="0" required defaultValue={c?.sort_order??0}/></label><Active value={c?.is_active}/></MutationForm></details>)}</>:
 <>{[null,...master.products].map(p=><details key={p?.id??"new"}><summary>{p?.name??"Add product"}</summary><MutationForm kind="master"><input type="hidden" name="kind" value="product"/><input type="hidden" name="id" value={p?.id??""}/><label>Name<input name="name" required defaultValue={p?.name}/></label><label>Local name<input name="local" defaultValue={p?.local_name}/></label><label>Category<select name="category" required defaultValue={p?.category_id}>{master.categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Description<textarea name="description" defaultValue={p?.description}/></label><label>Image asset path<input name="image" defaultValue={p?.image_path} placeholder="/assets/stitch/product.jpg"/></label><ProductChoices weights={p?.allowed_weights??[]} preparations={p?.preparations??[{name:""}]}/><Active value={p?.is_active}/></MutationForm></details>)}
 <details><summary>Add an existing product to a store</summary><MutationForm kind="master"><input type="hidden" name="kind" value="offering"/><label>Product<select name="product">{master.products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Store<select name="store">{context.stores.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><p>Starts Sold Out. Set its price and availability on Prices &amp; Availability.</p></MutationForm></details><p>Retire products to remove them from sale while preserving historical records.</p></>;
 } else if(section==="employees") {
 content=<StaffDirectory token={token} context={context}/>;
 } else if(section==="settings") {
 const settings=store?await staffRpc<{name:string;delivery:boolean;pickup:boolean;hours:unknown}>(token,"store_operations",{target_store:store.id}):null;
 content=settings&&store?<MutationForm kind="settings" key={store.id}><input type="hidden" name="store" value={store.id}/><label>Store name<input name="name" required defaultValue={settings.name}/></label>{(["delivery","pickup"] as const).map(name=><label key={name}>{name==="delivery"?"Delivery":"Store pickup"}<select name={name} defaultValue={String(settings[name])}><option value="true">Enabled</option><option value="false">Disabled</option></select></label>)}<label>Opening hours (JSON by day)<textarea name="hours" required defaultValue={JSON.stringify(settings.hours)}/></label><p>Use day keys mon–sun with opens/closes intervals, for example {"{\"mon\":[{\"opens\":\"09:00\",\"closes\":\"18:00\"}]}"}. Missing days are closed.</p></MutationForm>:<p>No accessible stores.</p>;
 } else content=<p>Select an available workspace section.</p>;
 return <div className="trait-admin admin-live"><header><Link className="admin-wordmark" href={base+"/dashboard"}>TRAIT<span>FISH &amp; MEAT HUB</span></Link><p>{context.role} · {context.name}</p><form action={signOut}><button className="admin-button secondary">Sign out</button></form></header><nav aria-label="Staff navigation">{staffSections.filter(s=>canAccessSection(context.role,s)).map(s=><Link key={s} href={base+"/"+s} aria-current={s===section?"page":undefined}>{sectionLabels[s]}</Link>)}</nav><main><h1>{sectionLabels[section]}</h1>{["prices","settings","orders","payments","reports","dashboard"].includes(section)&&<nav aria-label="Stores">{context.stores.map(s=><Link key={s.id} href={base+"/"+section+"?store="+s.id} aria-current={store?.id===s.id?"page":undefined}>{s.name}</Link>)}</nav>}{content}{section==="settings"&&<><BusinessPolicy token={token}/><DeliverySettings token={token} store={store?.id}/></>}{section==="employees"&&<OperationalForm operation="provision" label="Invite staff"><label>Name<input name="name" required maxLength={160}/></label><label>Work email<input name="email" type="email" required/></label><label>Role<select name="role"><option>EMPLOYEE</option>{context.role==="ADMIN"&&<option>OWNER</option>}</select></label><label>Store<select name="store">{context.stores.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label></OperationalForm>}</main></div>;
}
