import { staffRpc } from "@/lib/admin/server";
import { formatMoney } from "@/lib/format";
type Report={intake:{count:number;paise:number};fulfillment:{fulfilledPaise:number;cancelled:number};collections:{method:string;collectedPaise:number;refundedPaise:number}[];balances:{status:string;count:number;amountPaise:number}[];products:{name:string;category:string;grams:number;intakePaise:number}[];activity:{name:string;action:string;count:number}[]};
export async function BusinessReport({token,store,days=30,fromDate,untilDate}:{token:string;store?:string;days?:number;fromDate?:string;untilDate?:string}){
 if(!store)return <p>No accessible stores.</p>;
 const period=[1,7,30,365].includes(days)?days:30;
 let until=new Date(),from=new Date(until.getTime()-period*86400000);
 if(fromDate||untilDate){
  if(!/^\d{4}-\d{2}-\d{2}$/.test(fromDate??"")||!/^\d{4}-\d{2}-\d{2}$/.test(untilDate??""))return <p role="alert">Choose both start and end dates.</p>;
  from=new Date(fromDate+"T00:00:00Z");until=new Date(untilDate+"T00:00:00Z");
  if(!Number.isFinite(+from)||!Number.isFinite(+until)||+until<=+from||+until-+from>366*86400000)return <p role="alert">Choose a valid period of at most 366 days. The end date is exclusive.</p>;
 }
 const r=await staffRpc<Report>(token,"operations_report",{target_store:store,from_date:from.toISOString(),until_date:until.toISOString()});
 const outstanding=r.balances.filter(p=>["PENDING","VERIFYING","FAILED"].includes(p.status)).reduce((sum,p)=>sum+Number(p.amountPaise),0);
 return <section><form method="get"><input name="store" type="hidden" value={store}/><label>Period<select name="days" defaultValue={period}>{[1,7,30,365].map(d=><option key={d} value={d}>Past {d} days</option>)}</select></label><label>Start date (UTC)<input type="date" name="from" defaultValue={fromDate}/></label><label>End date (UTC, exclusive)<input type="date" name="until" defaultValue={untilDate}/></label><p>Leave both dates empty to use the rolling period.</p><button className="admin-button">Update report</button></form><p>Events from {from.toISOString()} to {until.toISOString()} (UTC).</p><dl><dt>New orders</dt><dd>{r.intake.count}</dd><dt>Order intake</dt><dd>{formatMoney(Number(r.intake.paise))}</dd><dt>Sales fulfilled during this period</dt><dd>{formatMoney(Number(r.fulfillment.fulfilledPaise))}</dd><dt>Cancellations during this period</dt><dd>{r.fulfillment.cancelled}</dd><dt>Current outstanding on non-cancelled orders (all dates)</dt><dd>{formatMoney(outstanding)}</dd></dl><h2>Collections and completed refunds</h2>{r.collections.map(p=><p key={p.method}>{p.method}: collected {formatMoney(Number(p.collectedPaise))}; refunded {formatMoney(Number(p.refundedPaise))}</p>)}<h2>Current payment states (all dates)</h2>{r.balances.map(p=><p key={p.status}>{p.status}: {p.count} · {formatMoney(Number(p.amountPaise))}</p>)}<h2>Product and category order intake</h2><p>Raw ordered weight and intake include subsequently cancelled orders.</p><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Product</th><th>Category</th><th>Raw grams</th><th>Intake</th></tr></thead><tbody>{r.products.map((p,i)=><tr key={i}><td>{p.name}</td><td>{p.category}</td><td>{p.grams}</td><td>{formatMoney(Number(p.intakePaise))}</td></tr>)}</tbody></table></div><h2>Staff activity in this store</h2>{r.activity.map((a,i)=><p key={i}>{a.name} · {a.action.replaceAll("_"," ")}: {a.count}</p>)}</section>;
}
