"use client";
import { useState } from "react";
import { Panel } from "./ui";
const tabs = ["Store details", "Delivery & pickup", "Order settings", "Payment configuration", "Business & invoices"];
export function Settings({ notify }: { notify: (message?: string) => void }) {
 const [tab, setTab] = useState(tabs[0]); const [draft, setDraft] = useState<Record<string, string>>({ storeName: "TRAIT · Sample store", timezone: "Asia/Kolkata", delivery: "Enabled", pickup: "Enabled", currency: "INR", fulfilment: "Earliest available", businessName: "TRAIT Fish & Meat Hub", invoicePrefix: "TFM", cash: "Enabled", online: "Not configured" });
 const [dirty, setDirty] = useState(false);
 function field(name: string, label: string, options?: { type?: string; placeholder?: string; choices?: string[]; required?: boolean; help?: string }) { return <label key={name}>{label}{options?.choices ? <select value={draft[name] ?? options.choices[0]} onChange={e => { setDraft({ ...draft, [name]: e.target.value }); setDirty(true); }}>{options.choices.map(value => <option key={value}>{value}</option>)}</select> : <input type={options?.type ?? "text"} value={draft[name] ?? ""} placeholder={options?.placeholder} required={options?.required} min={options?.type === "number" ? 0 : undefined} step={options?.type === "number" ? "0.01" : undefined} maxLength={300} onChange={e => { setDraft({ ...draft, [name]: e.target.value }); setDirty(true); }} />}{options?.help && <small>{options.help}</small>}</label>; }
 return <><div className="admin-settings-tabs" role="group" aria-label="Settings sections">{tabs.map(item => <button key={item} aria-pressed={item === tab} onClick={() => setTab(item)}>{item}</button>)}</div><form onSubmit={e => { e.preventDefault(); setDirty(false); notify("Settings draft saved for this page only. No business configuration was changed."); }}><Panel title={tab}><div className="admin-form-grid">
 {tab === tabs[0] && <>{field("storeName", "Store name", { required: true })}{field("phone", "Support phone", { type: "tel", placeholder: "To be confirmed" })}{field("address", "Store address", { placeholder: "To be confirmed" })}{field("pincode", "Store pincode", { placeholder: "To be confirmed" })}{field("hours", "Opening hours", { placeholder: "To be confirmed" })}{field("timezone", "Timezone", { choices: ["Asia/Kolkata"] })}</>}
 {tab === tabs[1] && <>{field("delivery", "Home delivery", { choices: ["Enabled", "Disabled"] })}{field("pickup", "Store pickup", { choices: ["Enabled", "Disabled"] })}{field("areas", "Delivery areas / pincodes", { placeholder: "To be confirmed", help: "Eligibility must ultimately be validated on the server." })}{field("deliveryFee", "Delivery fee (INR)", { type: "number", placeholder: "Undecided" })}{field("minimum", "Minimum order (INR)", { type: "number", placeholder: "Undecided" })}{field("pickupInstructions", "Pickup instructions", { placeholder: "Instructions for customers" })}</>}
 {tab === tabs[2] && <>{field("fulfilment", "Fulfilment timing", { choices: ["Earliest available"], help: "Customer-selected time slots are outside the MVP." })}{field("accepting", "Accepting new orders", { choices: ["Enabled", "Paused"] })}{field("cancellation", "Cancellation policy", { placeholder: "Policy to be confirmed" })}{field("cashLimit", "Employee cash collection limit (INR)", { type: "number", placeholder: "Policy undecided", help: "Saving a draft does not enable cash collection." })}{field("visibility", "Employee order visibility policy", { placeholder: "To be confirmed" })}</>}
 {tab === tabs[3] && <>{field("cash", "Cash on delivery / at pickup", { choices: ["Enabled", "Disabled"] })}{field("online", "Online / UPI", { choices: ["Not configured"] })}<div className="admin-notice admin-wide"><strong>Payment provider not selected</strong><p>Provider connection, merchant verification, webhook status and settlement controls will appear here after integration. Do not enter API keys, webhook secrets or payment credentials.</p><button className="admin-button secondary" type="button" disabled>Connect provider · coming with integration</button></div></>}
 {tab === tabs[4] && <>{field("businessName", "Business display name", { required: true })}{field("legalName", "Legal business name", { placeholder: "To be confirmed" })}{field("taxId", "GST / tax registration", { placeholder: "Requirements to be confirmed" })}{field("currency", "Currency", { choices: ["INR"] })}{field("invoicePrefix", "Invoice prefix")}{field("invoiceAddress", "Invoice address")}{field("invoiceFooter", "Invoice footer / notes", { placeholder: "To be confirmed" })}<p className="admin-muted admin-wide">Tax calculation, invoice numbering and legal requirements need business approval before live use. This preview does not issue invoices.</p></>}
 </div><div className="admin-settings-save"><p className="admin-muted">{dirty ? "Unsaved preview changes" : "Presentation settings only"}</p><button className="admin-button" type="submit">Save preview settings</button></div></Panel></form></>;
}

